site_name: CCSync Docs
site_url: https://github.com/its-me-abhishek/ccsync
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: cyan 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: cyan

# plugins:
  # - social
  # - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/its-me-abhishek/ccsync

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list

markdown_extensions:
  - tables

copyright: |
  &copy; 2025 <a href="https://github.com/its-me-abhishek/ccsync"  target="_blank" rel="noopener">CCSync</a>
